language: node_js
node_js:
- '10'
script:
- yarn run lint
- yarn run test
deploy:
  provider: npm
  email: zinovik@gmail.com
  on:
    repo: zinovik/z-games-no-thanks
    branch: master
  skip_cleanup: true
  api_key:
    secure: XSX++MRPD5c0lNbKRiTR1Yv+qBrtKCPWvrKje9sqk4mH6ymNU93IAOupDeWv8lcdjOczBpTsnCtvBMNbkgyaZHZFCiaBsBOjkxiMsi3B05sN5NPqOUX+7vEx7krO4TFDfdosq2AetVrVHqZ7rqvhck9ND8eWDs04wf4i9duw5RfZHa6KGTjjEbVpRjCfdvsAUtFtlDC/JzYGfEVt4DnCN8KhCd2ta7/yfE+e+kZFPLkoQaVOVd9drHoLB8JVXEe8DRmgPIF3BNUEDUKZPfD08bHeDYsehkYCLlPdoXblL34cDGmlpec4DaQjAd0ukoHoDFLfm2/OX56Hmy93QRRRSur6yvh3TURseqNsX04dDZ+Wixo+tkb4MzQ7KPZKv9zL8oxvbXSsuUEPCAEhFTrtKlOmlj2/CkdBxXuZ4Z+2yE4W/8bu0+MQjUve1+L1B8yHuG9xSMdyzs9L/47LkL1ClAxQhxtKOVUuvllSa3qmEgcZCN4sgGoRDjlWPyisbjyhraa5HR4OLz2fFWzDTFUy5nLX6KqwVBiNgbK4o8khMXskVnzjJt8j1llUHXuE3BrjB/7py29qQovDPbrTLxwbDuivJKHKDlOmCHK10OMPBnM9EXy3oJeyU/tAjHe+4rkRdZueYZnKnXpUDxWbcgFuzemm8BmLhZHYctkfga+Y8zU=
